### ISSUE TITLE
Error: error writing file: error extracting file: archive/tar: invalid tar header

### ISSUE THREAD

**Issue by cmartinezv** [replicate/pget#110]
Always get this error if I add -x for extraction. Extraction of [.tar/.tar.gz] works with tar xvf file.tar.gz.
I'm using pget@0.3.4

2023-12-12T13:01:14+01:00 | DEBUG | [ Extract ] extractor=tar status=starting
Error: error writing file: error extracting file: archive/tar: invalid tar header

Any idea what's going on ?

Thanks

**Comment by tempusfrangit** [comment]
I think you're trying to extract a .tar.gz. We currently do not have .gz support in pget. The reasoning for this is primarily due to Pget being built for downloading machine learning weights, and the weights historically do not compress well.

This is something that can be added to our enhancements list for pget. We are also happy to accept contributions for features like gz support!

**Comment by cmartinezv** [comment]
Okkk, then you should change --help as says tar.gz as example, I've tried with tar though and didn't work either.
I've also compare download a .zip file without extraction using wget vs pget and I got better results with wget. Is that normal ?
Usage:
pget [flags] <url> <dest>
pget [command]

Examples:
  pget https://example.com/file.tar.gz file.tar.gz

**Comment by tempusfrangit** [comment]
I'll definitely get the example fixed! That is definitely a mistake. 

Do you have an example that file that is failing?

PGET can produce worse behavior that curl and wget in some scenarios specifically depending on how many concurrent requests are made and the speed of your disks. 

On my home 1gigabit internet I can regularly run into wire-speed limits and other downloaders can perform better. Within the replicate infrastructure we regularly see > 1-2 gigabyte a second across the public internet, 3+ for optimized cache, and in ideal scenarios > 7 gigabytes/s. 

I also readily admit we are in a rapid iteration cycle and will be returning to do another performance tune on pget in the near future. We did see a reduction in sheer throughput between v0.1.1 and current. 

We have some planned near term enhancements.

**Comment by tempusfrangit** [comment]
example tar working for me. Also there was a recent change made that handles hard-links in tar:

```
🐟 ❯ ./pget -x https://weights.replicate.delivery/default/sdxl/safety-1.0.tar ./safety
2023-12-12T07:34:38-08:00 | INFO  | [ Initiating ] dest=./safety minimum_chunk_size=16M url=https://weights.replicate.delivery/default/sdxl/safety-1.0.tar
2023-12-12T07:34:38-08:00 | INFO  | [ Redirect ] redirect_url=https://storage.googleapis.com/replicate-weights/sdxl/safety-1.0.tar url=https://weights.replicate.delivery/default/sdxl/safety-1.0.tar
2023-12-12T07:34:47-08:00 | INFO  | [ Complete ] dest=./safety download_elapsed=8.601s download_throughput="71 MB/s" size="608 MB" total_elapsed=8.824s write_elapsed=0.223s write_throughput="2.7 GB/s
```

**Comment by tempusfrangit** [comment]
Help-string fix issue is #113

**Comment by tempusfrangit** [comment]
This is where an evaluation of a few things plays into it.

If the set of weights is on the smaller side, it may be easiest to bake them into the image container. However, the larger the image the longer the delay on a cold boot. If you have reasonably fast serving of the weights you can use pget to download them at setup time. For private models you'll need to keep in mind the costs associated with setup time.

The multifile method of downloading with pget (new as of v0.1.1) tends to be very efficient and pulling down many files and limiting concurrency. I can't specifically advise you on the best approach via a github issue. I can give you the information you need to evaluate the options.

Look into PGET's --concurrency and --min-chunk-size settings they can help improve downloads (too many chunks for a small file is much worse than too few). Additionally if you have many files to download consider using the `multifile` mode.

If you can provide me with a .tar file that is broken, I'm happy to look into the code (I would not be surprised if there was more edge cases in tar files that would break pget, it's not the area we've been spending time improving). Otherwise I'll goahead and mark this issue closed. 

There are a few other resources (including our discord) that may help you determine which approach of getting the weights into your container is the best for you.

**Comment by tempusfrangit** [comment]
Feel free to reopen this issue if there are specific issues with the tar extraction on non-gzipped tar files.

**Comment by cmartinezv** [comment]
The issue was related to my hosting, switching to GCP solved the achive/tar invalid header.
