### ISSUE TITLE
Bug: pget -x can't handle symlinks (sometimes)

### ISSUE THREAD

**Issue by jd7h** [replicate/pget#86]
Hi there! I was putting a bunch of model files in a tar using
`tar -c -f model.tar .`, and upon extraction with `pget -x model.tar some_folder`, I got the error:
```
Error: error writing file: error extracting file: unsupported file type for 
./snapshots/2227ac38c9f16105cb0412e7cab4759978a8fd90/preprocessor_config.json, typeflag 1
```

I could fix this by using
`tar -c -h --hard-dereference -f model.tar .`, which dereferences all soft and hard links in `.`.

Here you find an example tar for which pget (version 0.3.1) fails: [symlink_faulty.tar](https://jd7h.com/dump/symlink_faulty.tar). Using `tar -x` instead of `pget -x` did work.
I tried to make a minimal tar with symlinks by hand, but then `pget -x example.tar some_folder` worked fine.

**Comment by tempusfrangit** [comment]
Thanks for the bug report and the reproduction steps.

It points to something we're doing wrong with the symlink handler.

**Comment by tempusfrangit** [comment]
Typeflag 1 is `TypeLink    = '1' // Hard link` - we do not have code to support hardlinks. We should probably address that and ensure we cover *all* the types in an extract refactor (the `pkg/extract/tar.go` file has largely been left untouched since the inception of pget.

@jd7h I think you don't have symlinks you have hard links and tar does preserve them. I think this is a case where we need to wire up the additional typeflag and should be low amounts of code.

**Comment by tempusfrangit** [comment]
@jd7h https://github.com/replicate/pget/releases/tag/v0.3.2 This should be fixed now in 0.3.2 release

**Comment by tempusfrangit** [comment]
This was a lot more complex than expected. But 🎉 complete and verified to work with the supplied tar file.

**Comment by tempusfrangit** [comment]
@jd7h - FYI there was a bug in the tagging. I've re-tagged and re-published. The old tag may have missed the extract bug. I'll bump to 0.3.3 to be sure
